
STEAM_REGIONS = {
    "us": "United States",
    "ca": "Canada",
    "mx": "Mexico",
    "cr": "Costa Rica",
    "pa": "Panama",
    "sv": "El Salvador",
    "gt": "Guatemala",
    "hn": "Honduras",
    "ni": "Nicaragua",
    "bz": "Belize",
    "bs": "Bahamas",
    "pr": "Puerto Rico",
    "do": "Dominican Republic",
    "cu": "Cuba",
    "jm": "Jamaica",
    "tt": "Trinidad and Tobago",
    "ar": "Argentina",
    "bo": "Bolivia",
    "br": "Brazil",
    "cl": "Chile",
    "co": "Colombia",
    "ec": "Ecuador",
    "gy": "Guyana",
    "py": "Paraguay",
    "pe": "Peru",
    "sr": "Suriname",
    "uy": "Uruguay",
    "ve": "Venezuela",
    "gf": "French Guiana",
    "fk": "Falkland Islands",
    "al": "Albania",
    "ad": "Andorra",
    "at": "Austria",
    "by": "Belarus",
    "be": "Belgium",
    "ba": "Bosnia and Herzegovina",
    "bg": "Bulgaria",
    "hr": "Croatia",
    "cy": "Cyprus",
    "cz": "Czech Republic",
    "dk": "Denmark",
    "ee": "Estonia",
    "fi": "Finland",
    "fr": "France",
    "de": "Germany",
    "gi": "Gibraltar",
    "gr": "Greece",
    "hu": "Hungary",
    "is": "Iceland",
    "ie": "Ireland",
    "im": "Isle of Man",
    "it": "Italy",
    "je": "Jersey",
    "xk": "Kosovo",
    "lv": "Latvia",
    "li": "Liechtenstein",
    "lt": "Lithuania",
    "lu": "Luxembourg",
    "mt": "Malta",
    "md": "Moldova",
    "mc": "Monaco",
    "me": "Montenegro",
    "nl": "Netherlands",
    "mk": "North Macedonia",
    "no": "Norway",
    "pl": "Poland",
    "pt": "Portugal",
    "ro": "Romania",
    "ru": "Russia",
    "sm": "San Marino",
    "rs": "Serbia",
    "sk": "Slovakia",
    "si": "Slovenia",
    "es": "Spain",
    "se": "Sweden",
    "ch": "Switzerland",
    "ua": "Ukraine",
    "gb": "United Kingdom",
    "gg": "Guernsey",
    "ae": "United Arab Emirates",
    "bh": "Bahrain",
    "il": "Israel",
    "iq": "Iraq",
    "ir": "Iran",
    "jo": "Jordan",
    "kw": "Kuwait",
    "lb": "Lebanon",
    "om": "Oman",
    "qa": "Qatar",
    "sa": "Saudi Arabia",
    "sy": "Syria",
    "tr": "Turkey",
    "ye": "Yemen",
    "dz": "Algeria",
    "ao": "Angola",
    "bw": "Botswana",
    "cm": "Cameroon",
    "eg": "Egypt",
    "gh": "Ghana",
    "ke": "Kenya",
    "ly": "Libya",
    "ma": "Morocco",
    "mz": "Mozambique",
    "na": "Namibia",
    "ng": "Nigeria",
    "sn": "Senegal",
    "za": "South Africa",
    "tz": "Tanzania",
    "tn": "Tunisia",
    "ug": "Uganda",
    "zm": "Zambia",
    "zw": "Zimbabwe",
    "af": "Afghanistan",
    "bd": "Bangladesh",
    "bt": "Bhutan",
    "in": "India",
    "mv": "Maldives",
    "np": "Nepal",
    "pk": "Pakistan",
    "lk": "Sri Lanka",
    "bn": "Brunei",
    "kh": "Cambodia",
    "id": "Indonesia",
    "la": "Laos",
    "my": "Malaysia",
    "mm": "Myanmar",
    "ph": "Philippines",
    "sg": "Singapore",
    "th": "Thailand",
    "tl": "Timor-Leste",
    "vn": "Vietnam",
    "cn": "China",
    "hk": "Hong Kong",
    "jp": "Japan",
    "kr": "South Korea",
    "mo": "Macau",
    "mn": "Mongolia",
    "tw": "Taiwan",
    "au": "Australia",
    "fj": "Fiji",
    "nz": "New Zealand",
    "pg": "Papua New Guinea",
}